-- Live Supabase schema (introspected 2026-08-06) for MISSED-CALL-PROJECT.
-- REFERENCE ONLY — not an apply migration. See docs/supabase/README.md for apply order.
-- App code in src/db.js maps to these tables. Do not invent alternate names.

-- tenants
--   id uuid PK
--   created_at timestamptz
--   business_name text NOT NULL
--   sautikit_virtual_number text NOT NULL  (pending:<auth_user_id> until DID pool assign)
--   whatsapp_notification_number text NOT NULL
--   alert_email text        (email fallback for leads/escalation; alert_email.sql)
--   llm_system_prompt text  (compiled for voice engine — not edited raw in Desk)
--   business_hours text     (owner-facing; see tenant_business_profile.sql)
--   services_offered text   (owner-facing)
--   agent_name text         (receptionist intro name; default Receptionist)
--   agent_tone text         (professional | friendly | empathetic | localized)
--   team_directory jsonb    ([{name, role, phone}]; knowledge_acquisition_phase1.sql)
--   faqs jsonb              ([{question, answer}]; knowledge_acquisition_phase1.sql)
--   hours_schedule jsonb    (weekly open hours; hours_schedule.sql — used live for open/closed)
--   after_hours_mode text   (serve | message; after_hours_mode.sql)
--   services_catalog jsonb  ([{name, price_range, notes, out_of_scope}]; services_catalog.sql)
--   vertical text           (general | retail | home_services | hospitality; business_operating_model.sql)
--   handoff_mode text       (callback | live_transfer; business_operating_model.sql)
--   business_locations jsonb ([{label,address,landmark,directions,coverage_notes}])
--   business_policies jsonb ({returns,delivery,payment,deposit,cancellation,warranty,other})
--   daily_bulletin jsonb    ([{id,text,active,starts_at,ends_at}]; daily_bulletin.sql)
--   voice_languages text[]  (auto: en, sw, sheng — see voice_languages.sql; locals later)
--   voice_language_other text  (reserved)
--   wallet_balance_kes numeric          (one prepaid KES wallet — see one_wallet_billing.sql)
--   wallet_low_balance_kes numeric      (UI threshold; default 200)
--   billing_enforcement text            (soft | hard | off)
--   soft_spend_limit_enabled boolean    (owner opt-in; default false — wallet_soft_spend_limit.sql)
--   soft_spend_limit_kes numeric        (monthly soft budget KES; warn only)
--   telecom_wallet_balance_kes numeric  (DEPRECATED — mirrored from wallet_balance_kes)
--   ai_wallet_balance_usd numeric       (DEPRECATED — AI bundled into KES wallet)
--   is_active boolean
--
-- wallet_ledger  (append-only; see one_wallet_billing.sql)
--   id uuid PK
--   created_at timestamptz
--   tenant_id uuid → tenants.id
--   kind text (topup | call_charge | line_rental | admin_adjustment | …)
--   amount_kes numeric  (+ credit / − debit)
--   balance_after_kes numeric
--   reference_type text
--   reference_id text   (idempotency key with kind+tenant)
--   note text
--   metadata jsonb
--   owner_user_id uuid → auth.users.id  (added in multi_tenant_onboarding.sql)
--
-- contacts  (see contacts_and_requests.sql)
--   id uuid PK, tenant_id, phone, name, notes, last_reason, metadata, timestamps
--
-- service_requests  (see contacts_and_requests.sql)
--   id uuid PK, tenant_id, contact_id, call_id
--   request_type (hold|enquiry|order|callback|other)
--   status (open|fulfilled|cancelled)
--   item, quantity, when_text, notes, caller_name, caller_phone, metadata
--
-- tenant_members  (user ↔ tenant mapping; see multi_tenant_onboarding.sql)
--   id uuid PK
--   created_at timestamptz
--   user_id uuid → auth.users.id
--   tenant_id uuid → tenants.id
--   role text ('owner' | 'admin' | 'member')
--   unique (user_id, tenant_id)
--
-- sautikit_did_pool  (Phase C; see did_number_pool.sql)
--   id uuid PK
--   e164 text unique
--   status text ('available' | 'assigned' | 'reserved' | 'disabled')
--   tenant_id uuid → tenants.id
--   assigned_at timestamptz
--   notes text

-- calls
--   id uuid PK
--   created_at timestamptz
--   tenant_id uuid NOT NULL → tenants.id
--   caller_number text NOT NULL
--   sautikit_call_sid text  (unique; also stores Twilio CallSid during Phase 1)
--   status text
--   duration_seconds int
--   ai_processing_minutes numeric  (set by voice engine from duration; wallet metering)
--   lead_status text  (new | contacted | resolved — see lead_status.sql)
--   sentiment text
--   summary text  (JSON blob for name/reason/whatsapp_sent/to_number/provider/…)

-- transcripts  (one row per utterance)
--   id uuid PK
--   created_at timestamptz
--   call_id uuid NOT NULL → calls.id
--   speaker text NOT NULL   ('caller' | 'agent' | 'system')
--   text_content text NOT NULL
--   latency_ms int

-- Storage bucket: call-recordings (private)

-- Owner RLS (Sprint 1) — apply docs/supabase/owner_rls.sql
--   Enables RLS on tenant_members, tenants, calls, transcripts.
--   Owners SELECT/UPDATE via auth.uid() membership in tenant_members.
--   service_role (voice engine + Super Admin + signup provisioner) bypasses RLS.

-- Optional seed for single-tenant / smoke tests:
-- insert into public.tenants (
--   business_name, sautikit_virtual_number, whatsapp_notification_number, is_active
-- ) values (
--   'Jirani Home Services', '+254709221536', '+254119774470', true
-- );
--
-- If an older smoke DID is still stored, update it:
-- update public.tenants
-- set sautikit_virtual_number = '+254709221536'
-- where sautikit_virtual_number = '+254200000001';
