-- Live Supabase schema (introspected 2026-08-06) for MISSED-CALL-PROJECT.
-- App code in src/db.js maps to these tables. Do not invent alternate names.

-- tenants
--   id uuid PK
--   created_at timestamptz
--   business_name text NOT NULL
--   sautikit_virtual_number text NOT NULL  (pending:<auth_user_id> until DID pool assign)
--   whatsapp_notification_number text NOT NULL
--   llm_system_prompt text  (compiled for voice engine — not edited raw in Desk)
--   business_hours text     (owner-facing; see tenant_business_profile.sql)
--   services_offered text   (owner-facing)
--   agent_name text         (receptionist intro name; default Receptionist)
--   agent_tone text         (professional | friendly | empathetic | localized)
--   team_directory jsonb    ([{name, role, phone}]; knowledge_acquisition_phase1.sql)
--   faqs jsonb              ([{question, answer}]; knowledge_acquisition_phase1.sql)
--   voice_languages text[]  (auto: en, sw, sheng — see voice_languages.sql; locals later)
--   voice_language_other text  (reserved)
--   telecom_wallet_balance_kes numeric
--   ai_wallet_balance_usd numeric
--   is_active boolean
--   owner_user_id uuid → auth.users.id  (added in multi_tenant_onboarding.sql)
--
-- tenant_members  (user ↔ tenant mapping; see multi_tenant_onboarding.sql)
--   id uuid PK
--   created_at timestamptz
--   user_id uuid → auth.users.id
--   tenant_id uuid → tenants.id
--   role text ('owner' | 'admin' | 'member')
--   unique (user_id, tenant_id)
--
-- sautikit_did_pool  (Phase C; see did_number_pool.sql)
--   id uuid PK
--   e164 text unique
--   status text ('available' | 'assigned' | 'reserved' | 'disabled')
--   tenant_id uuid → tenants.id
--   assigned_at timestamptz
--   notes text

-- calls
--   id uuid PK
--   created_at timestamptz
--   tenant_id uuid NOT NULL → tenants.id
--   caller_number text NOT NULL
--   sautikit_call_sid text  (unique; also stores Twilio CallSid during Phase 1)
--   status text
--   duration_seconds int
--   ai_processing_minutes numeric  (set by voice engine from duration; wallet metering)
--   lead_status text  (new | contacted | resolved — see lead_status.sql)
--   sentiment text
--   summary text  (JSON blob for name/reason/whatsapp_sent/to_number/provider/…)

-- transcripts  (one row per utterance)
--   id uuid PK
--   created_at timestamptz
--   call_id uuid NOT NULL → calls.id
--   speaker text NOT NULL   ('caller' | 'agent' | 'system')
--   text_content text NOT NULL
--   latency_ms int

-- Storage bucket: call-recordings (private)

-- Owner RLS (Sprint 1) — apply docs/supabase/owner_rls.sql
--   Enables RLS on tenant_members, tenants, calls, transcripts.
--   Owners SELECT/UPDATE via auth.uid() membership in tenant_members.
--   service_role (voice engine + Super Admin + signup provisioner) bypasses RLS.

-- Optional seed for single-tenant / smoke tests:
-- insert into public.tenants (
--   business_name, sautikit_virtual_number, whatsapp_notification_number, is_active
-- ) values (
--   'Jirani Home Services', '+254709221536', '+254119774470', true
-- );
--
-- If an older smoke DID is still stored, update it:
-- update public.tenants
-- set sautikit_virtual_number = '+254709221536'
-- where sautikit_virtual_number = '+254200000001';
